name: Docker Image CI for GHCR

on:
  push

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   services:
  #     mysql:
  #       image: mysql:8.3
  #       env:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: auth
  #       ports:
  #         - 3306:3306
  #       options: >-
  #         --health-cmd="mysqladmin ping"
  #         --health-interval=10s
  #         --health-timeout=5s
  #         --health-retries=3

  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.12'
        
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
  #   - name: Run tests
  #     env:
  #       DB_HOST: 127.0.0.1
  #       DB_PORT: 3306
  #       DB_USER: root
  #       DB_PASSWORD: root
  #     run: |
  #       pytest

  build-and-push:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mail-service:latest -t ghcr.io/${{ github.repository_owner }}/mail-service:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/mail-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/mail-service:${{ github.sha }}

  update-gitops:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          repository: lukasdrothler/k8s-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: finyed/overlays/dev

      - name: Update Image Tag
        run: |
          # Navigate to the directory containing kustomization.yaml
          cd finyed/overlays/dev
          
          # Update the image tag using sed
          sed -i '/name: ghcr.io\/lukasdrothler\/mail-service/,/newTag:/ s|newTag: .*|newTag: ${{ github.sha }}|' finyed/overlays/dev/kustomization.yaml

      - name: Commit and Push Changes
        run: |
          cd finyed/overlays/dev
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes before committing
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "update: mail-service image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi